### ISSUE TITLE
TypeError: object is not a Function

### ISSUE THREAD

**Issue by sethmurphy18** [VeliovGroup/Meteor-Files#145]
Ok, so for some reason, I am getting an error related to the constructor. I wish I had more debug info, sadly I don't because my app won't even launch...it just keeps crashing on boot.

```sh
=> Started proxy.
=> Started MongoDB.
W20160713-11:17:20.286(-4)? (STDERR)
W20160713-11:17:21.714(-4)? (STDERR) C:\Users\Seth\AppData\Local\.meteor\packages\meteor-tool\1.3.4_4\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:280
W20160713-11:17:21.718(-4)? (STDERR)                                            throw(ex);
W20160713-11:17:21.725(-4)? (STDERR)                                                  ^
W20160713-11:17:21.728(-4)? (STDERR) TypeError: object is not a function
W20160713-11:17:21.730(-4)? (STDERR)     at meteorInstall.server.collections.ProfilePictures.js (server/collections/ProfilePictures.js:43:23)
W20160713-11:17:21.733(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
W20160713-11:17:22.077(-4)? (STDERR)     at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
W20160713-11:17:22.088(-4)? (STDERR)     at C:\Users\Seth\Projects\Website\.meteor\local\build\programs\server\app\app.js:218:1
W20160713-11:17:22.093(-4)? (STDERR)     at C:\Users\Seth\Projects\Website\.meteor\local\build\programs\server\boot.js:297:10
W20160713-11:17:22.100(-4)? (STDERR)     at Array.forEach (native)
W20160713-11:17:22.108(-4)? (STDERR)     at Function._.each._.forEach (C:\Users\Seth\AppData\Local\.meteor\packages\meteor-tool\1.3.4_4\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20160713-11:17:22.110(-4)? (STDERR)     at C:\Users\Seth\Projects\Website\.meteor\local\build\programs\server\boot.js:133:5
=> Exited with code: 8
```

As for my source code, I have double and triple checked that I am typing everything correctly, I just cannot figure out where the issue is.

```javascript
import { EJSON } from 'meteor/ejson';
import { Meteor } from 'meteor/meteor';
import { Random } from 'meteor/random';
import { _ } from 'meteor/underscore';
import gcloud from 'google-cloud-storage-standalone';
import FilesCollection from 'meteor/ostrio:files';
import SimpleSchema from 'meteor/aldeed:simple-schema';

var googleCloudStorage, bucket, bucketInfo, bound, ProfilePictures = {};

let googleCloudCredentials = EJSON.parse(Assets.getText('google-cloud-account.json'));

// Intialize Google Cloud Storage
googleCloudStorage = gcloud.storage({
  projectId: 'com-eagerestwolf-website-2',
  config: {
    credentials: {
      client_email: googleCloudCredentials.client_email,
      private_key: googleCloudCredentials.private_key
    }
  }
});

// Set which bucket to use
bucket = googleCloudStorage.bucket('com-eagerestwolf-website-storage-1');

// Get the bucket information so we have the URL
bucket.getMetadata(function(error, metadata, apiResponse) {
  "use strict";
  if (error) {
    console.error(error);
  } else {
    bucketInfo = metadata;
  }
});

bound = Meteor.bindEnvironment(function(callback) {
  "use strict";
  return callback();
});

ProfilePictures = new FilesCollection({
  debug: false,
  throttle: false,
  storagePath: 'assets/app/uploads/profile_pictures',
  collectionName: 'profile-pictures',
  allowClientCode: false,
  
  onbeforeunloadMessage: function () {
    "use strict";
    return 'Upload is still in progress! Upload will be aborted if you leave this page!';
  },

  onBeforeUpload: function (file) {
    "use strict";
    if (file.size <= 31457280 && /png|jpg|jpeg/i.test(file.ext)) {
      return true;
    } else {
      return 'Please upload a png or jpeg image, with size equal or less than 30MB';
    }
  },

  onAfterUpload: function(fileRef) {
    "use strict";
    var self = this;
    _.each(fileRef.versions, function(vRef) {
      var filePath = "images/profile_pictures/" + (Random.id()) + "." + fileRef.extension;
      
      var options = {
        destination: filePath
      };

      bucket.upload(fileRef.path, options, function(error, file) {
        var upd;
        if (error) {
          console.error(error);
        } else {
          upd = {
            $set: {}
          };
          upd['$set']["meta.pipeFrom"] = bucketInfo.selfLink + '/' + filePath;
          upd['$set']["meta.pipePath"] = filePath;
          self.collection.update({
            _id: fileRef._id
          }, upd, function (error) {
            if (error) {
              console.error(error);
            } else {
              self.unlink(self.collection.findOne(fileRef._id), fileRef.version);
            }
          });
        }
      });
    });
  }
});

ProfilePictures.collection.attachSchema(new SimpleSchema(ProfilePictures.schema));

// Intercept file's collection remove method to remove file from Google Cloud Storage
var _origRemove = ProfilePictures.remove;

ProfilePictures.remove = function(search) {
  "use strict";
  var cursor = this.collection.find(search);
  cursor.forEach(function(fileRef) {
    _.each(fileRef.versions, function(vRef) {
      var ref;
      if (vRef !== null ? (ref = vRef.meta) !== null ? ref.pipePath : void 0 : void 0) {
        bucket.deleteFiles(vRef.meta.pipePath, function(error) {
          bound(function() {
            if (error) {
              console.error(error);
            }
          });
        });
      }
    });
  });
  // Call the original removal method
  _origRemove.call(this, search);
};

ProfilePictures.deny({
  insert: function() {
    "use strict";
    return true;
  },
  update: function() {
    "use strict";
    return true;
  },
  remove: function() {
    "use strict";
    return true;
  }
});
```

**Comment by sethmurphy18** [comment]
Ok, turns out the issue is this module does not support ES6 style importing...that might be something good to add in an upcoming release.

**Comment by dr-dimitru** [comment]
@sethmurphy18 thank you for info. Any help around it? How to make it supported?

**Comment by sethmurphy18** [comment]
I'm taking a look into it now. I'm gonna run some tests on my side. I may end up having to do it the `React.Component` way and force the user to create a class and override default properties they don't need, which is essentially what you are already doing with the `config` object. I submit a PR on dev, once I think I have something.

**Comment by dr-dimitru** [comment]
@sethmurphy18 thank you

**Comment by sethmurphy18** [comment]
No problem

**Comment by sethmurphy18** [comment]
There is one slightly major issue...Coffeescript doesn't support ES6 natively. I'm gonna see if I can work around it. I need to export this class.

**Comment by dr-dimitru** [comment]
What if we just add `export.jsx` to the package and export `FilesCollection` class?

**Comment by sethmurphy18** [comment]
I can look into trying that. I need to figure out how to import the class from the original CoffeeScript. I need to make it abstract. What ideally needs to happen to make it ES6 compatible is to allow an class that inherits the `FileCollection` class, and override the properties directly, without the `constructor()`

**Comment by sethmurphy18** [comment]
I'm exporting the CoffeeScript to Javascript, then I will give you an idea what I mean

**Comment by dr-dimitru** [comment]
Why? Try to use global `__coffeescriptShare` object.

In coffeescript:
```coffeescript
__coffeescriptShare.FilesCollection = FilesCollection
```

In JSX:
```jsx
export {FilesCollection} from __coffeescriptShare;
```

**Comment by sethmurphy18** [comment]
I wasn't aware of that honestly. I am not super familiar with CoffeeScript, I usually work with pure JS and Babel. Let me see what the result of that is.

**Comment by dr-dimitru** [comment]
Waiting for it

**Comment by sethmurphy18** [comment]
Ok, that worked. No server errors...no client errors. Pushing code now.

**Comment by dr-dimitru** [comment]
Great, thank you

**Comment by sethmurphy18** [comment]
No problem

**Comment by sethmurphy18** [comment]
On a side note, you might want to add a note to the docs that to import this module, all you need to do is in your js or jsx file include the line.

```javascript
import {FilesCollection} from 'meteor/ostrio:files'
```

**Comment by sethmurphy18** [comment]
PR submitted...on to my next project...lol

**Comment by dr-dimitru** [comment]
I left a question on PR for you

**Comment by dr-dimitru** [comment]
Done in https://github.com/VeliovGroup/Meteor-Files/commit/3c190bb4cf92ae8be7f6cc4696e17c2dab72e142
I found a way to keep everything inside `.coffee` file, take a look

**Comment by sethmurphy18** [comment]
I saw that...I didn't realize Coffeescript could do that.

**Comment by dr-dimitru** [comment]
@sethmurphy18 ,
Thank you for contribution, it's really improved package

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Files)
 - Stat on [Atmosphere](https://atmospherejs.com/ostrio/files)
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Files)

**Comment by sethmurphy18** [comment]
No problem...I see a need and I fill a need.
