### ISSUE TITLE
When set S3 in Demo I got errors

### ISSUE THREAD

**Issue by fortunto2** [VeliovGroup/Meteor-Files#158]
Hi, thanks for nice package

but i have error 

i set in demo/lib/files.collection.coffee S3 Settings
and when start 

** TypeError: Cannot call method 'putFile' of undefined**

```

I20160722-22:18:00.282(5)? [FilesCollection] [serve(assets/app/uploads/uploadedFiles/DZiQe3PEtGXimyrsd.png, original)] [200]
I20160722-22:18:00.735(5)? Exception in callback of async function: TypeError: Cannot call method 'putFile' of undefined
I20160722-22:18:00.736(5)?     at lib/files.collection.coffee:202:18
I20160722-22:18:00.736(5)?     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
I20160722-22:18:00.736(5)?     at sendToStorage (lib/files.collection.coffee:196:11)
I20160722-22:18:00.736(5)?     at lib/files.collection.coffee:224:11
I20160722-22:18:00.736(5)?     at server/image-processing.coffee:13:16
I20160722-22:18:00.737(5)?     at server/image-processing.coffee:1:53
I20160722-22:18:00.737(5)?     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:110:1)
I20160722-22:18:00.737(5)?     at packages/meteor/dynamics_nodejs.js:123:1
I20160722-22:18:00.737(5)?     at finish (server/image-processing.coffee:8:23)
I20160722-22:18:00.738(5)?     at server/image-processing.coffee:86:23

```

**Comment by fortunto2** [comment]
sorry, i wrong set settings in settings.json... not in env.var
