### ISSUE TITLE
Susbscriptions return nothing 9 out of 10, then returns as expected

### ISSUE THREAD

**Issue by yanickrochon** [VeliovGroup/Meteor-Files#249]
I declared a collection using the [GridFS integration](https://github.com/VeliovGroup/Meteor-Files/wiki/GridFS-Integration) (**note** it is [*not* working](http://stackoverflow.com/questions/39839527/files-are-not-uploaded-with-meteors-ostriofiles-filescollection)...) and publish this collection as

```
Meteor.publish('users.avatars', function (userId) {
  if (userId) {
    return Images.find({ 'userId': userId }).cursor;
  } else {
    return Images.find().cursor;
  }
});
```

Then, on the client, I register for this collection

```
class UserProfileAvatar extends TrackerReact(Component) {

  constructor() {
    super(...arguments);

    this.state = {
      subscription: {
        avatars: Meteor.subscribe('users.avatars', this.props.user)
      }
    };
  }

  ready() {
    return this.state.subscription.avatars.ready();
  }

  getUserAvatar(user) {
    const avatar = Images.findOne({ userId: user._id });

    return avatar && avatar.path || DEFAULT_AVATAR;
  }

  render() {
    if (!this.ready()) {
      return ( <div>Loading...</div> );
    }

    const { user } = this.props;
    const avatarPath = this.getUserAvatar(user);

    return (
      <img className="responsive-img avatar" src={ avatarPath } alt={ user.username } />
    );
  }
}
```

However the subscription does not return anything most of the time.

This happens in `meteor@1.4.1.1` and `ostrio:files@1.7.3`.

**Comment by dr-dimitru** [comment]
Hi @yanickrochon 

1. To generate downloadable url to the file use [`link` method](https://github.com/VeliovGroup/Meteor-Files/wiki/link)
2. Files is stored in GridFS (MongoDB)

**Comment by yanickrochon** [comment]
Thank you for the `link()` method. I am not sure why `storagePath` is necessary, then, as nothing is written on the path. This is quite confusing.

As for the subscriptions, the publish method still returns an empty cursor most of the time. I'm not sure why.

**Comment by dr-dimitru** [comment]
> This is quite confusing.

It used by lib internally before you move files to GridFS

> As for the subscriptions, the publish method still returns an empty cursor most of the time. I'm not sure why.

Show your publish/subscribe code. And make sure docs exists in collection on server

**Comment by yanickrochon** [comment]
... the very first post of this issue shows the publish and subscribe code already. And, when the collection is properly published (1 out of 10 or something), it works. Why wouldn't it work? All my other collections and subscription work!

**Comment by yanickrochon** [comment]
I removed GridFS from the collection, and I still get the same behavior; the cursor will be `ready`, on the client side, only about 1 / 10 refresh, and the subscription's `ready()` method is returning false most of the time. On the server side, I see the query, and all seems to work well.

As I said, I have half a dozen collections, and all subscriptions and collections behave as expected. But this one... is simply never ready most of the time.

**Comment by dr-dimitru** [comment]
try to publish like this:

```js
Meteor.publish('users.avatars', function (userId) {
  if (userId) {
    return Images.collection.find({ 'userId': userId });
  } else {
    return Images.collection.find();
  }
});
```

 1. Idk what problem here is as it is regular Meteor's Mongo Collection, it's definitely on your end
 2. `I removed GridFS from the collect....` not related, GridFS used separately in your case
 3. You're doing the whole thing wrong. You shouldn't publish/subscribe to the `Images` collection (*this is for your case only*). After image is uploaded it's more reasonable to add it to user's `profile` without adding extra-dependencies:

```js
# Somewhere in onAfterUpload:
var file = _.pick(fileObj, '_downloadRoute', '_id', 'extension', '_collectionName');
Meteor.users.update({_id: file.userId}, {
  $set: {
    'profile.avatar': file
  }
});
```

In a place where you need to get a link to the image:
```js
Images.link(Meteor.user().profile.avatar);
```

**Comment by yanickrochon** [comment]
Are you saying that GridFS is unnecessary, here? What's the point of GridFS, then?

**Comment by dr-dimitru** [comment]
> Are you saying that GridFS is unnecessary, here?

No, it's up to you what you're using for storage

> What's the point of GridFS, then?

Alternative storage to `FS`.

**Comment by dr-dimitru** [comment]
@yanickrochon I was saying you don't need to publish/subscribe `Images` collection docs

**Comment by yanickrochon** [comment]
> dk what problem here is as it is regular Meteor's Mongo Collection, it's definitely on your end

Well, I tried `return Images.collection.find();` and Meteor fails with 

```
Exception from sub users.avatars id pwRaRCwSgQgDxXBAT Error: Publish function can only return a Cursor or an array of Cursors
     at Subscription._publishHandlerResult (packages/ddp-server/livedata_server.js:1110:18)
     at Subscription._runHandler (packages/ddp-server/livedata_server.js:1041:10)
     at Session._startSubscription (packages/ddp-server/livedata_server.js:845:9)
     at Session.sub (packages/ddp-server/livedata_server.js:617:12)
     at packages/ddp-server/livedata_server.js:551:43
```

So, no, this is not seem to be a regular Meteor Mongo Collection.

**Comment by dr-dimitru** [comment]
> So, no, this is not seem to be a regular Meteor Mongo Collection.

The `Images.collection` is regular collection.


Could you please post how do you define `Images`, and output of `console.log(Images.collection)` and `console.log(Images.collection.find())`?

**Comment by yanickrochon** [comment]
Wait... I'm confused again.

This is from the `README.md` file :

```js
var Images = new FilesCollection({
  collectionName: 'Images',
  allowClientCode: false, // Disallow remove files from Client
  onBeforeUpload: function (file) {
    // Allow upload files under 10MB, and only in png/jpg/jpeg formats
    if (file.size <= 10485760 && /png|jpg|jpeg/i.test(file.extension)) {
      return true;
    } else {
      return 'Please upload image, with size equal or less than 10MB';
    }
  }
});

if (Meteor.isClient) {
  Meteor.subscribe('files.images.all');
}

if (Meteor.isServer) {
  Meteor.publish('files.images.all', function () {
    return Images.find().cursor;
  });
}
```

1. The collection is declared as `var Images = new FilesCollection({ ... });`
2. The collection is published as `Images.find().cursor;`
3. I just noticed that you are suggesting `Images.collection.find();`

So, ok, here we go :

1. I am declaring *my* collection as `const Images = new FilesCollection({ ... });`
2. I have tried `Images.find().cursor;` which lead to this issue
3. I have tried `Images.collection.find();` with no better results.

There is nothing else to add, no hidden code or initialization; the options passed to the `FilesCollection` function is literally a copy/paste of the [`GridFS`](https://github.com/VeliovGroup/Meteor-Files/wiki/GridFS-Integration), which I realize is not necessary, so I even tried to set minimal options 

```json
{
  collectionName: 'images',
  allowClientCode: false,
  debug: Meteor.isServer && process.env.NODE_ENV === 'development',
}
```

with no change; the collection is not published most of the time.

As I already stated, I have several other collections and subscriptions, and this is the only implementation that gives me this issue.

This is the output you requested :

```
I20161004-09:25:01.562(-4)? { _makeNewID: [Function],
I20161004-09:25:01.564(-4)?   _transform: null,
I20161004-09:25:01.564(-4)?   _connection:
I20161004-09:25:01.564(-4)?    Server {
I20161004-09:25:01.565(-4)?      options:
I20161004-09:25:01.565(-4)?       { heartbeatInterval: 15000,
I20161004-09:25:01.565(-4)?         heartbeatTimeout: 15000,
I20161004-09:25:01.565(-4)?         respondToPings: true },
I20161004-09:25:01.565(-4)?      onConnectionHook:
I20161004-09:25:01.565(-4)?       { nextCallbackId: 1,
I20161004-09:25:01.566(-4)?         callbacks: [Object],
I20161004-09:25:01.566(-4)?         bindEnvironment: true,
I20161004-09:25:01.566(-4)?         exceptionHandler: 'onConnection callback' },
I20161004-09:25:01.566(-4)?      publish_handlers:
I20161004-09:25:01.566(-4)?       { MeteorToys: [Function],
I20161004-09:25:01.566(-4)?         cursorcounts: [Function],
I20161004-09:25:01.566(-4)?         UniConfig: [Function],
I20161004-09:25:01.567(-4)?         'meteor.loginServiceConfiguration': [Function],
I20161004-09:25:01.567(-4)?         _roles: [Function],
I20161004-09:25:01.567(-4)?         meteor_autoupdate_clientVersions: [Function] },
I20161004-09:25:01.567(-4)?      universal_publish_handlers: [ [Function] ],
I20161004-09:25:01.567(-4)?      method_handlers:
I20161004-09:25:01.567(-4)?       { '/MeteorToys.Impersonate/insert': [Function],
I20161004-09:25:01.567(-4)?         '/MeteorToys.Impersonate/update': [Function],
I20161004-09:25:01.567(-4)?         '/MeteorToys.Impersonate/remove': [Function],
I20161004-09:25:01.568(-4)?         '/MeteorToys.JetSetter/insert': [Function],
I20161004-09:25:01.568(-4)?         '/MeteorToys.JetSetter/update': [Function],
I20161004-09:25:01.568(-4)?         '/MeteorToys.JetSetter/remove': [Function],
I20161004-09:25:01.568(-4)?         '/MeteorToys.Mongol/insert': [Function],
I20161004-09:25:01.568(-4)?         '/MeteorToys.Mongol/update': [Function],
I20161004-09:25:01.569(-4)?         '/MeteorToys.Mongol/remove': [Function],
I20161004-09:25:01.569(-4)?         '/MeteorToys.AutoPub/insert': [Function],
I20161004-09:25:01.569(-4)?         '/MeteorToys.AutoPub/update': [Function],
I20161004-09:25:01.569(-4)?         '/MeteorToys.AutoPub/remove': [Function],
I20161004-09:25:01.569(-4)?         '/MeteorToys.Email/insert': [Function],
I20161004-09:25:01.569(-4)?         '/MeteorToys.Email/update': [Function],
I20161004-09:25:01.569(-4)?         '/MeteorToys.Email/remove': [Function],
I20161004-09:25:01.569(-4)?         '/MeteorToys.Result/insert': [Function],
I20161004-09:25:01.570(-4)?         '/MeteorToys.Result/update': [Function],
I20161004-09:25:01.570(-4)?         '/MeteorToys.Result/remove': [Function],
I20161004-09:25:01.570(-4)?         '/MeteorToys.Throttle/insert': [Function],
I20161004-09:25:01.570(-4)?         '/MeteorToys.Throttle/update': [Function],
I20161004-09:25:01.570(-4)?         '/MeteorToys.Throttle/remove': [Function],
I20161004-09:25:01.570(-4)?         '/MeteorToys.Credentials/insert': [Function],
I20161004-09:25:01.570(-4)?         '/MeteorToys.Credentials/update': [Function],
I20161004-09:25:01.570(-4)?         '/MeteorToys.Credentials/remove': [Function],
I20161004-09:25:01.571(-4)?         Mongol_verifyDoc: [Function],
I20161004-09:25:01.571(-4)?         MeteorToys_init: [Function],
I20161004-09:25:01.571(-4)?         MeteorToys_remove: [Function],
I20161004-09:25:01.571(-4)?         MeteorToys: [Function],
I20161004-09:25:01.571(-4)?         MeteorToysRegistry: [Function],
I20161004-09:25:01.571(-4)?         Mongol_update: [Function],
I20161004-09:25:01.571(-4)?         Mongol_remove: [Function],
I20161004-09:25:01.572(-4)?         Mongol_duplicate: [Function],
I20161004-09:25:01.572(-4)?         Mongol_insert: [Function],
I20161004-09:25:01.572(-4)?         Mongol_getCollections: [Function],
I20161004-09:25:01.572(-4)?         Mongol_resetCollection: [Function],
I20161004-09:25:01.572(-4)?         Mongol_resetMeteorToys: [Function],
I20161004-09:25:01.572(-4)?         Mongol_resetAll: [Function],
I20161004-09:25:01.573(-4)?         MeteorToys_impersonate: [Function],
I20161004-09:25:01.573(-4)?         MeteorToys_impersonate_account: [Function],
I20161004-09:25:01.573(-4)?         MeteorToys_acct_seed: [Function],
I20161004-09:25:01.573(-4)?         MeteorToys_account_keywords: [Function],
I20161004-09:25:01.573(-4)?         MeteorToys_dni: [Function],
I20161004-09:25:01.573(-4)?         MeteorToys_Shell: [Function],
I20161004-09:25:01.573(-4)?         MeteorToy_4: [Function],
I20161004-09:25:01.575(-4)?         MeteorToys_x: [Function],
I20161004-09:25:01.576(-4)?         MeteorToy_y: [Function],
I20161004-09:25:01.576(-4)?         MeteorToys_autopub: [Function],
I20161004-09:25:01.577(-4)?         MeteorToy_d: [Function],
I20161004-09:25:01.578(-4)?         MeteorToy_f: [Function],
I20161004-09:25:01.578(-4)?         MeteorToys_throttle: [Function],
I20161004-09:25:01.579(-4)?         MeteorToys_throttle_disable: [Function],
I20161004-09:25:01.579(-4)?         '/universe_configs/insert': [Function],
I20161004-09:25:01.580(-4)?         '/universe_configs/update': [Function],
I20161004-09:25:01.580(-4)?         '/universe_configs/remove': [Function],
I20161004-09:25:01.580(-4)?         '/users/insert': [Function],
I20161004-09:25:01.580(-4)?         '/users/update': [Function],
I20161004-09:25:01.580(-4)?         '/users/remove': [Function],
I20161004-09:25:01.581(-4)?         login: [Function],
I20161004-09:25:01.581(-4)?         logout: [Function],
I20161004-09:25:01.581(-4)?         logoutOtherClients: [Function],
I20161004-09:25:01.581(-4)?         getNewToken: [Function],
I20161004-09:25:01.581(-4)?         removeOtherTokens: [Function],
I20161004-09:25:01.581(-4)?         configureLoginService: [Function],
I20161004-09:25:01.582(-4)?         changePassword: [Function: changePassword],
I20161004-09:25:01.582(-4)?         forgotPassword: [Function: forgotPassword],
I20161004-09:25:01.582(-4)?         resetPassword: [Function: resetPassword],
I20161004-09:25:01.582(-4)?         verifyEmail: [Function: verifyEmail],
I20161004-09:25:01.583(-4)?         createUser: [Function: createUser],
I20161004-09:25:01.584(-4)?         ATRemoveService: [Function],
I20161004-09:25:01.584(-4)?         ATCreateUserServer: [Function],
I20161004-09:25:01.584(-4)?         ATResendVerificationEmail: [Function],
[--- snip: bunch of collections insert, update, remove functions ---]
I20161004-09:25:01.589(-4)?         '/users.avatars/insert': [Function],
I20161004-09:25:01.589(-4)?         '/users.avatars/update': [Function],
I20161004-09:25:01.589(-4)?         '/users.avatars/remove': [Function],
I20161004-09:25:01.589(-4)?         '/__pre_users.avatars/insert': [Function],
I20161004-09:25:01.589(-4)?         '/__pre_users.avatars/update': [Function],
I20161004-09:25:01.590(-4)?         '/__pre_users.avatars/remove': [Function],
I20161004-09:25:01.592(-4)?         '_FilesCollectionRemove_users.avatars': [Function],
I20161004-09:25:01.593(-4)?         '_FilesCollectionStart_users.avatars': [Function],
I20161004-09:25:01.593(-4)?         '_FilesCollectionWrite_users.avatars': [Function],
I20161004-09:25:01.593(-4)?         '_FilesCollectionAbort_users.avatars': [Function] },
I20161004-09:25:01.593(-4)?      sessions: {},
I20161004-09:25:01.593(-4)?      stream_server:
I20161004-09:25:01.593(-4)?       StreamServer {
I20161004-09:25:01.593(-4)?         registration_callbacks: [Object],
I20161004-09:25:01.594(-4)?         open_sockets: [],
I20161004-09:25:01.594(-4)?         prefix: '/sockjs',
I20161004-09:25:01.594(-4)?         server: [Object] } },
I20161004-09:25:01.594(-4)?   _collection:
I20161004-09:25:01.594(-4)?    { find: [Function: bound ],
I20161004-09:25:01.594(-4)?      findOne: [Function: bound ],
I20161004-09:25:01.595(-4)?      insert: [Function: bound ],
I20161004-09:25:01.595(-4)?      update: [Function: bound ],
I20161004-09:25:01.595(-4)?      upsert: [Function: bound ],
I20161004-09:25:01.595(-4)?      remove: [Function: bound ],
I20161004-09:25:01.595(-4)?      _ensureIndex: [Function: bound ],
I20161004-09:25:01.595(-4)?      _dropIndex: [Function: bound ],
I20161004-09:25:01.595(-4)?      _createCappedCollection: [Function: bound ],
I20161004-09:25:01.595(-4)?      dropCollection: [Function: bound ],
I20161004-09:25:01.596(-4)?      rawCollection: [Function: bound ],
I20161004-09:25:01.596(-4)?      _getDb:
I20161004-09:25:01.596(-4)?       EventEmitter {
I20161004-09:25:01.596(-4)?         domain: null,
I20161004-09:25:01.596(-4)?         _events: {},
I20161004-09:25:01.596(-4)?         _eventsCount: 0,
I20161004-09:25:01.596(-4)?         _maxListeners: undefined,
I20161004-09:25:01.596(-4)?         s: [Object],
I20161004-09:25:01.597(-4)?         serverConfig: [Getter],
I20161004-09:25:01.597(-4)?         bufferMaxEntries: [Getter],
I20161004-09:25:01.597(-4)?         databaseName: [Getter] } },
I20161004-09:25:01.597(-4)?   _name: 'users.avatars',
I20161004-09:25:01.597(-4)?   _driver:
I20161004-09:25:01.597(-4)?    { mongo:
I20161004-09:25:01.597(-4)?       MongoConnection {
I20161004-09:25:01.597(-4)?         _observeMultiplexers: [Object],
I20161004-09:25:01.598(-4)?         _onFailoverHook: [Object],
I20161004-09:25:01.598(-4)?         db: [Object],
I20161004-09:25:01.598(-4)?         _primary: '127.0.0.1:3001',
I20161004-09:25:01.598(-4)?         _oplogHandle: [Object],
I20161004-09:25:01.598(-4)?         _docFetcher: [Object] } },
I20161004-09:25:01.598(-4)?   _restricted: false,
I20161004-09:25:01.598(-4)?   _insecure: undefined,
I20161004-09:25:01.598(-4)?   _validators:
I20161004-09:25:01.599(-4)?    { insert: { allow: [], deny: [] },
I20161004-09:25:01.599(-4)?      update: { allow: [], deny: [] },
I20161004-09:25:01.599(-4)?      remove: { allow: [], deny: [] },
I20161004-09:25:01.599(-4)?      upsert: { allow: [], deny: [] },
I20161004-09:25:01.599(-4)?      fetch: [],
I20161004-09:25:01.599(-4)?      fetchAllFields: false },
I20161004-09:25:01.599(-4)?   _prefix: '/users.avatars/' }
```

**Comment by dr-dimitru** [comment]
1. `Images.collection.find();` and `Images.find().cursor;` returns same cursor, I've asked you to check both in case there is bug or you're using outdated version of driver
 2. I see you're actually using collection name with dot `users.avatars`, right? If so, could you try to change it to the name without `.`? (*This shouldn't lead to the any issues, but it's better to check*)
 3. Yes, as I've said before `Images.collection` is regular `Mongo.Collection`, and `console.log` confirmed that 
 4. So what `console.log(Images.collection.find())` is returns?

**Comment by dr-dimitru** [comment]
And one more thing - Could you directly go to MongoDB and run same `find()` to see what is actually returning?

**Comment by yanickrochon** [comment]
I do use `meteor mongo` to test, and I can search without any issues.

```
meteor:PRIMARY> db['users.avatars'].find();
{ "_id" : "3Dbm65gnmnzkTPrvB", "name" : "test.jpg", "extension" : "jpg", "path" : "data/3Dbm65gnmnzkTPrvB.jpg", "meta" : {  }, "type" : "image/jpeg", "size" : 108148, "versi
ons" : { "original" : { "path" : "data/3Dbm65gnmnzkTPrvB.jpg", "size" : 108148, "type" : "image/jpeg", "extension" : "jpg", "meta" : { "gridFsFileId" : "57f2b426313ad9562846bb33
" } } }, "isVideo" : false, "isAudio" : false, "isImage" : true, "isText" : false, "isJSON" : false, "isPDF" : false, "_storagePath" : "data", "_downloadRoute" : "/cdn/storage",
 "_collectionName" : "users.avatars", "userId" : "WYWWAmMYAp4YtKsYZ", "public" : false }
{ "_id" : "n7xvAwQqqahpizYQL", "name" : "dnd_original.jpg", "extension" : "jpg", "path" : "data/n7xvAwQqqahpizYQL.jpg", "meta" : {  }, "type" : "image/jpeg", "size" : 679188, "v
ersions" : { "original" : { "path" : "data/n7xvAwQqqahpizYQL.jpg", "size" : 679188, "type" : "image/jpeg", "extension" : "jpg", "meta" : { "gridFsFileId" : "57f2bbf0313ad9562846
bb35" } } }, "isVideo" : false, "isAudio" : false, "isImage" : true, "isText" : false, "isJSON" : false, "isPDF" : false, "_storagePath" : "data", "_downloadRoute" : "/cdn/stora
ge", "_collectionName" : "users.avatars", "userId" : "WYWWAmMYAp4YtKsYZ", "public" : false }
```

Also, renaming the collection by removing the dot does not change anything. At first, it did seem to succeed more often (about 1 out of 3) but the more I refresh, the more I realized it was just a fluke.

The output of `console.log(Images.collection.find());` is

```
I20161004-10:03:10.467(-4)? Cursor {
I20161004-10:03:10.470(-4)?   _mongo:
I20161004-10:03:10.470(-4)?    MongoConnection {
I20161004-10:03:10.471(-4)?      _observeMultiplexers:
I20161004-10:03:10.471(-4)?       { '{"ordered":false,"collectionName":"__pre_users.avatars","selector":{},"options":{"transform":null}}': [Object],
I20161004-10:03:10.471(-4)?         '{"ordered":false,"collectionName":"users","selector":"_id":"WYWWAmMYAp4YtKsYZ"},"options":{"transform":null,"fields":{"profile":1,"username":1,"emails":1}}}': [Object],
I20161004-10:03:10.471(-4)?         '{"ordered":false,"collectionName":"users","selector":"_id":"WYWWAmMYAp4YtKsYZ","services.resume.loginTokens.hashedToken":"V/WTQI8pLcn+LW7HjHCERKoY0PNdM0oY6D5PM0otB7g="},"options":{"transform":null,"fields":{"_id":1}}}': [Object],
I20161004-10:03:10.472(-4)?         '{"ordered":false,"collectionName":"meteor_accounts_loginServiceConfiguration","selector":{},"options":{"transform":null,"fields":{"secret":0}}}': [Object],
I20161004-10:03:10.473(-4)?         '{"ordered":false,"collectionName":"universe_configs","selector":{"$or":[{"access":"public"},{"access":"WYWWAmMYAp4YtKsYZ"}]},"options":{"transform":null}}': [Object],
I20161004-10:03:10.473(-4)?         '{"ordered":false,"collectionName":"users","selector":{"_id":"WYWWAmMYAp4YtKsYZ"},"options":{"transform":null,"fields":{"roles":1}}}': [Object],
I20161004-10:03:10.473(-4)?         '{"ordered":false,"collectionName":"MeteorToys.Impersonate","selector":{},"options":{"transform":null,"limit":15}}': [Object],
I20161004-10:03:10.475(-4)?         '{"ordered":false,"collectionName":"MeteorToys.JetSetter","selector":{},"options":{"transform":null}}': [Object],
I20161004-10:03:10.475(-4)?         '{"ordered":false,"collectionName":"MeteorToys.AutoPub","selector":{},"options":{"transform":null}}': [Object],
I20161004-10:03:10.475(-4)?         '{"ordered":false,"collectionName":"MeteorToys.Throttle","selector":{},"options":{"transform":null}}': [Object],
I20161004-10:03:10.475(-4)?         '{"ordered":false,"collectionName":"MeteorToys.Email","selector":{},"options":{"transform":null,"sort":{"timestamp":1},"limit":15}}': [Object],
I20161004-10:03:10.476(-4)?         '{"ordered":false,"collectionName":"MeteorToys.Result","selector":{},"options":{"transform":null,"sort":{"timestamp":-1},"limit":15}}': [Object],
I20161004-10:03:10.476(-4)?         '{"ordered":false,"collectionName":"MeteorToys.Mongol","selector":{},"options":{"transform":null,"sort":{"Mongol_date":1},"limit":15}}': [Object],
I20161004-10:03:10.476(-4)?         '{"ordered":false,"collectionName":"users","selector":{"_id":{"$in":["WYWWAmMYAp4YtKsYZ"]}},"options":{"transform":null}}': [Object] },
I20161004-10:03:10.476(-4)?      _onFailoverHook:
I20161004-10:03:10.476(-4)?       { nextCallbackId: 25,
I20161004-10:03:10.476(-4)?         callbacks: [Object],
I20161004-10:03:10.477(-4)?         bindEnvironment: true },
I20161004-10:03:10.477(-4)?      db:
I20161004-10:03:10.477(-4)?       EventEmitter {
I20161004-10:03:10.477(-4)?         domain: null,
I20161004-10:03:10.477(-4)?         _events: {},
I20161004-10:03:10.477(-4)?         _eventsCount: 0,
I20161004-10:03:10.478(-4)?         _maxListeners: undefined,
I20161004-10:03:10.478(-4)?         s: [Object],
I20161004-10:03:10.478(-4)?         serverConfig: [Getter],
I20161004-10:03:10.478(-4)?         bufferMaxEntries: [Getter],
I20161004-10:03:10.478(-4)?         databaseName: [Getter] },
I20161004-10:03:10.478(-4)?      _primary: '127.0.0.1:3001',
I20161004-10:03:10.478(-4)?      _oplogHandle:
I20161004-10:03:10.479(-4)?       OplogHandle {
I20161004-10:03:10.479(-4)?         _oplogUrl: 'mongodb://127.0.0.1:3001/local',
I20161004-10:03:10.479(-4)?         _dbName: 'meteor',
I20161004-10:03:10.479(-4)?         _oplogLastEntryConnection: [Object],
I20161004-10:03:10.479(-4)?         _oplogTailConnection: [Object],
I20161004-10:03:10.479(-4)?         _stopped: false,
I20161004-10:03:10.479(-4)?         _tailHandle: [Object],
I20161004-10:03:10.479(-4)?         _readyFuture: [Object],
I20161004-10:03:10.479(-4)?         _crossbar: [Object],
I20161004-10:03:10.479(-4)?         _baseOplogSelector: [Object],
I20161004-10:03:10.480(-4)?         _catchingUpFutures: [],
I20161004-10:03:10.480(-4)?         _lastProcessedTS: [Object],
I20161004-10:03:10.480(-4)?         _onSkippedEntriesHook: [Object],
I20161004-10:03:10.480(-4)?         _entryQueue: [Object],
I20161004-10:03:10.480(-4)?         _workerActive: false },
I20161004-10:03:10.480(-4)?      _docFetcher: DocFetcher { _mongoConnection: [Circular], _callbacksForCacheKey: {} } },
I20161004-10:03:10.480(-4)?   _cursorDescription:
I20161004-10:03:10.480(-4)?    CursorDescription {
I20161004-10:03:10.480(-4)?      collectionName: 'users.avatars',
I20161004-10:03:10.480(-4)?      selector: {},
I20161004-10:03:10.481(-4)?      options: { transform: null } },
I20161004-10:03:10.481(-4)?   _synchronousCursor: null }
```

**Comment by dr-dimitru** [comment]
Looks good to me. You definitely should check how sub/pub works on your end. As I've said previously it's regular Mongo.Collection. For debugging I recommend `mongol` package.

Also I highly recommend to use [`audit-argument-checks`](https://docs.meteor.com/packages/audit-argument-checks.html) package, to make sure you're requesting data in according to planed architecture.

**Comment by yanickrochon** [comment]
Exactly, the reason more I don't understand what's going on. I have implemented many interfaces so far, and I am finalizing extra features (i.e. allowing users to change their avatars, associate files and media to various models, etc.) and I get this issue.

**Comment by dr-dimitru** [comment]
Hey @yanickrochon ,
Is this issue still persists?

**Comment by yanickrochon** [comment]
No, I am using [`temp`](https://www.npmjs.com/package/temp) along with GridFS, and so I simply pass the temp directory path and it works fine.

Perhaps this could be suggested as well, instead of having users create arbitrary directory and GridFS deleting the physical files anyhow.
