### ISSUE TITLE
S3: Invalid URI on piped requests

### ISSUE THREAD

**Issue by jonasbarsten** [VeliovGroup/Meteor-Files#273]
`Invalid URI "xxxx.cloudfront.net/files/GRf7sPtLcQkyCfAbw-original.pdf"`

I'm able to upload files to the bucket and see them when I enter xxxx.cloudfront.net/files/GRf7sPtLcQkyCfAbw-original.pdf in my browser, but the piping seems to fail.

Where may I have made a wrong turn?

`Error: Invalid URI "xxxx.cloudfront.net/files/GRf7sPtLcQkyCfAbw-original.pdf"
   at Request.init (/Users/jonasbarsten/Documents/meteor/artex.no/node_modules/request/request.js:274:31)
   at new Request (/Users/jonasbarsten/Documents/meteor/artex.no/node_modules/request/request.js:128:8)
   at request (/Users/jonasbarsten/Documents/meteor/artex.no/node_modules/request/index.js:54:10)
   at FilesCollection.interceptDownload (both/collections/s3.js:75:7)
   at FilesCollection.module.runModuleSetters.FilesCollection.download (/Users/jonasbarsten/Documents/meteor/artex.no/.meteor/local/build/programs/server/packages/ostrio_files.js:2987:18)
   at Object.handle (/Users/jonasbarsten/Documents/meteor/artex.no/.meteor/local/build/programs/server/packages/ostrio_files.js:1197:22)
   at next (/Users/jonasbarsten/.meteor/packages/webapp/.1.3.12.1kqnwqv++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:174:15)
   at Object.handle (packages/ostrio_cookies.js:515:17)
   at next (/Users/jonasbarsten/.meteor/packages/webapp/.1.3.12.1kqnwqv++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:174:15)
   at Function.app.handle (/Users/jonasbarsten/.meteor/packages/webapp/.1.3.12.1kqnwqv++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:182:3)`

**Comment by jonasbarsten** [comment]
I solved this by adding:

`if (path) {
    path = 'http://' + path;
    [...]
}`

to `interceptDownload()`

and also completing step 4, not just 1 - 3 (as stated in the docs) [here](https://github.com/Lepozepo/S3#create-your-amazon-s3) .

**Comment by dr-dimitru** [comment]
Hi @jonasbarsten ,

I'm glad you've solved this issue. I think `Follow steps 1-3 from...` should be replaced with actual steps. Would you like to send PR for this (*or I can update it myself*)?

**Comment by jonasbarsten** [comment]
Extremely new to GitHub, so probably best that you do it :)

Thanks for a great package btw!
— 
Jonas Barsten
+47 41 54 77 98

**Comment by lleoooell** [comment]
I reproduce this error and struggle on it a few minutes...here is what i saw if it helps someone : 

the answer by @jonasbarsten depends on how you setup your cfdomain variable...

if you setup it like this :
cfdomain = 'sdfgvdfvw.cloudfront.net';
http:// prefix will be missing, and the @jonasbarsten fix is the solution...

if you setup it like this :
cfdomain = 'http://sdfgvdfvw.cloudfront.net';
it should be quite ok, but take care not to end with '.net/', otherwise, the url wil be '.cloudfront.net//files/', so it will throw the error again.

**Comment by dr-dimitru** [comment]
Done in https://github.com/VeliovGroup/Meteor-Files/commit/1102cfa93b7870a7d5923d57b453ce9ee5b9a0db

Thank you all for contribution, and sorry for delay
