### ISSUE TITLE
ReferenceError: check is not defined with Meteor 1.1.0.2

### ISSUE THREAD

**Issue by jreinert** [VeliovGroup/Meteor-Files#32]
I can't start meteor because of the following error:

```
ReferenceError: check is not defined
    at new Files (packages/ostrio:files/files.coffee:147:5)
    at Files.allow.insert (packages/app-filestore/lib/files.js:1:1)
    at /home/jokke/code/projects/tagfs/.meteor/local/build/programs/server/packages/app-filestore.js:28:4
    at /home/jokke/code/projects/tagfs/.meteor/local/build/programs/server/packages/app-filestore.js:92:3
    at /home/jokke/code/projects/tagfs/.meteor/local/build/programs/server/boot.js:222:10
    at Array.forEach (native)
    at Function._.each._.forEach (/home/jokke/.meteor/packages/meteor-tool/.1.1.3.4sddkj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
    at /home/jokke/code/projects/tagfs/.meteor/local/build/programs/server/boot.js:117:5
```

**Comment by dr-dimitru** [comment]
Thank you for contribution, please update to [`v1.3.7`](https://github.com/VeliovGroup/Meteor-Files/releases/tag/v1.3.7)
