### ISSUE TITLE
Mach error on upload

### ISSUE THREAD

**Issue by jreinert** [VeliovGroup/Meteor-Files#34]
thanks for the fast fix of my last issue! Now I'm getting an error when uploading a file. Not sure if this is a bug or some misconfiguration on my side.

```
Exception while invoking method 'MeteorFileWrite27cbfcbe172a3d9bf03834c002d75f0926d0fa16f28594a4ac80e587325df05f' Error: Match error: Failed Match.OneOf or Match.Optional validation
    at checkSubtree (packages/check/match.js:244:1)
    at check (packages/check/match.js:32:1)
    at [object Object].Files._methods.(anonymous function) (packages/ostrio:files/files.coffee:266:9)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
    at packages/ddp/livedata_server.js:648:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp/livedata_server.js:647:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
    at packages/ddp/livedata_server.js:546:1
Sanitized and reported to the client as: Match failed [400]
```

**Comment by dr-dimitru** [comment]
Please post here your code

**Comment by jreinert** [comment]
``` javascript
Files = new Meteor.Files({
	collectionName: 'files',
	downloadRoute: '/files',
	protected: function () {
		return this.userId;
		//return fileObject.owner_id === userId;
	}
});
```

``` javascript
Files.collection.allow({
	insert: function (userId, fileObject) {
		return true;
	},
	update: function (userId, fileObject) {
		return true;
	},
	remove: function (userId, fileObject) {
		return true;
	}
});
```

``` javascript
Template.uploader.events({
	'change input': function (event, template) {
		var model = this;
		Files.insert({
			file: event.target.files[0],
			onUploaded: function (error, file) {
				if (error) {
					console.error(error.toString());
					return;
				}
				model.removeFile();
				model.setFile(file);
				template.isUploading.set(false);
				template.isCreatingThumb.set(true);
				Meteor.call('createThumb', file, function () {
					template.isCreatingThumb.set(false);
				});
			},
			onProgress: _.throttle(function (progress) {
				template.progress.set(progress);
			}, 500),
			onBeforeUpload: function () {
				template.isUploading.set(true);
				return true;
			},
			streams: 8
		});
	}
});
```

**Comment by dr-dimitru** [comment]
Please add meta as empty object (will fix it in further updates):
```javascript
Template.uploader.events({
    'change input': function (event, template) {
        var model = this;
        Files.insert({
            file: event.target.files[0],
            meta: {},
            onUploaded: function (error, file) {
                if (error) {
                    console.error(error.toString());
                    return;
                }
                model.removeFile();
                model.setFile(file);
                template.isUploading.set(false);
                template.isCreatingThumb.set(true);
                Meteor.call('createThumb', file, function () {
                    template.isCreatingThumb.set(false);
                });
            },
            onProgress: _.throttle(function (progress) {
                template.progress.set(progress);
            }, 500),
            onBeforeUpload: function () {
                template.isUploading.set(true);
                return true;
            },
            streams: 8
        });
    }
});
```

**Comment by jreinert** [comment]
Thanks, that did fix the upload. I don't know if it's related but i get the following error for using `findOne('some_id')`:

```
Exception in template helper: Error: Match error: Failed Match.OneOf or Match.Optional validation
    at checkSubtree (http://localhost:3002/packages/check.js?ac81167b8513b85b926c167bba423981b0c4cf9c:279:11)
    at check (http://localhost:3002/packages/check.js?ac81167b8513b85b926c167bba423981b0c4cf9c:67:5)
    at Files.Meteor.Files.Files.findOne (http://localhost:3002/packages/ostrio_files.js?0ecbd02e467ab89ae275801ed4c36fba1a44ad28:715:5)
    at MapperModel.extend.getFile (http://localhost:3002/packages/app-document-model.js?9ece7483dc9ff0d444e80e682e0fca02411a07ba:59:16)
    at Template.uploader.helpers.file (http://localhost:3002/packages/app-uploader.js?6930264f5f957947d8448f8952a2c5a31fcbcec6:164:15)
    at bindDataContext (http://localhost:3002/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2880:16)
    at Blaze._wrapCatchingExceptions (http://localhost:3002/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:1651:16)
    at http://localhost:3002/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2928:66
    at Function.Template._withTemplateInstanceFunc (http://localhost:3002/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:3476:12)
    at wrapHelper (http://localhost:3002/packages/blaze.js?a5c324925e5f6e800a4c618d71caf2848b53bf51:2927:27)
```

**Comment by dr-dimitru** [comment]
Set `debug` property on collection to `true`, to see what are you sending into this function.
I see it is coming from `onUploaded`, could you provide more code?

**Comment by dr-dimitru** [comment]
@jreinert any news on your end?

**Comment by dr-dimitru** [comment]
Closed due to silence on issue starter end
