### ISSUE TITLE
File rwlock issue when file size > 1gb

### ISSUE THREAD

**Issue by haojia321** [VeliovGroup/Meteor-Files#365]
Issue happens intermittently and mostly happens when upload a big file(> 1GB).
This is error:

W20170226-19:54:32.922(-5)? (STDERR) C:\Users\Hao.YEFENG\AppData\Local\.meteor\packages\npm-mongo\2.2.16_1\npm\node_modules\mongodb\lib\utils.js:98
W20170226-19:54:32.925(-5)? (STDERR)     process.nextTick(function() { throw err; });
W20170226-19:54:32.933(-5)? (STDERR)                                   ^
W20170226-19:54:32.934(-5)? (STDERR) MongoError: assertion C:\data\mci\src\src\mongo/util/concurrency/rwlock.h:204
W20170226-19:54:32.939(-5)? (STDERR)     at Function.MongoError.create (C:\Users\Hao.YEFENG\AppData\Local\.meteor\packages\npm-mongo\2.2.16_1\npm\node_modules\mongodb-core\lib\error.js:31:11)
W20170226-19:54:32.940(-5)? (STDERR)     at toError (C:\Users\Hao.YEFENG\AppData\Local\.meteor\packages\npm-mongo\2.2.16_1\npm\node_modules\mongodb\lib\utils.js:114:22)
W20170226-19:54:32.943(-5)? (STDERR)     at C:\Users\Hao.YEFENG\AppData\Local\.meteor\packages\npm-mongo\2.2.16_1\npm\node_modules\mongodb\lib\collection.js:1048:67
W20170226-19:54:32.945(-5)? (STDERR)     at C:\Users\Hao.YEFENG\AppData\Local\.meteor\packages\npm-mongo\2.2.16_1\npm\node_modules\mongodb-core\lib\connection\pool.js:455:18
W20170226-19:54:32.946(-5)? (STDERR)     at nextTickCallbackWith0Args (node.js:436:9)
W20170226-19:54:32.947(-5)? (STDERR)     at process._tickCallback (node.js:365:13)
=> Exited with code: 1

**Comment by haojia321** [comment]
Closing the issue since I found most likely it is because im running a 32 bit mongodb which only support 2gb data maximum.
