### ISSUE TITLE
.serve() Can't set headers after they are sent

### ISSUE THREAD

**Issue by mgscreativa** [VeliovGroup/Meteor-Files#433]
Hi! I'm using ostrio:files v1.7.13 and meteor v1.4.4.2. I have created a server module file to hook collection **interceptDownload** event and after call it, I get **Can't set headers after they are sent.** in the server console. Maybe there's an issue with .serve() method. I got the **interceptDownload** code from latest **Meteor-Files-Demos**

## Collection (/imports/api/images/images):
```
import { Meteor } from 'meteor/meteor';
import { FilesCollection } from 'meteor/ostrio:files';

const Images = new FilesCollection({
  debug: true,
  throttle: false,
  storagePath: () => `${Meteor.absolutePath}/uploads`,
  downloadRoute: '/uploads',
  collectionName: 'Images',
  allowClientCode: false,
  onBeforeUpload: (file) => {
    if (file.size > 10485760) {
      return 'Please upload image, with size equal or less than 10MB.';
    }

    if (!/png|jpg|jpeg/i.test(file.extension)) {
      return `${file.extension}'s files are not allowed for upload.`;
    }

    return true;
  },
  onAfterUpload: (fileRef) => {
    import { onAfterUpload } from '../../modules/server/upload-files';

    onAfterUpload(fileRef);
  },
  onBeforeRemove: (cursor) => {
    if (Meteor.isServer) {
      console.log('Running onBeforeRemove on the server');
    } else {
      console.log('Running onBeforeRemove on the client');
    }

    import { onBeforeRemove } from '../../modules/server/upload-files';

    onBeforeRemove(cursor);
  },
  interceptDownload: (http, fileRef, version) => {
    import { interceptDownload } from '../../modules/server/upload-files';

    interceptDownload(http, fileRef, version);
  },
});

export default Images;
```
## Server Module File (/imports/modules/server/upload-files):
```
import { Meteor } from 'meteor/meteor';
import request from 'request';
import Dropbox from 'dropbox';
import gm from 'gm';
import fs from 'fs';
import Images from '../../api/images/images';

const bound = Meteor.bindEnvironment(callback => callback());
const dropboxPrefix = '/images';
const dbx = new Dropbox({ accessToken: process.env.DROPBOX_TOKEN });

const makeUrl = (path, file, version) => {
  dbx.sharingCreateSharedLink({ path, short_url: false }).then((response) => {
    bound(() => {
      const upd = {
        $set: {},
      };

      upd.$set[`versions.${version}.meta.pipeFrom`] = response.url.replace('dl=0', 'raw=1');
      upd.$set[`versions.${version}.meta.pipePath`] = path;

      Images.update({ _id: file._id }, upd, (error) => {
        if (error) {
          return console.error(error);
        }

        Images.unlink(Images.findOne(file._id), version);
      });
    });
  }).catch((err) => {
    console.error(err);
  });
};

const writeToDB = (file, version, data) => {
  dbx.filesUpload({
    path: `${dropboxPrefix}/${file._id}-${version}.${file.extension}`,
    contents: data,
    autorename: false,
  }).then((response) => {
    bound(() => {
      makeUrl(response.path_display, file, version);
    });
  }).catch((err) => {
    bound(() => {
      console.error(err);
    });
  });
};

const readFile = (file, vRef, version) => {
  fs.readFile(vRef.path, (error, data) => {
    bound(() => {
      if (error) {
        return console.error(error);
      }

      writeToDB(file, version, data);
    });
  });
};

const sendToStorage = (file) => {
  _.each(file.versions, (vRef, version) => {
    readFile(file, vRef, version);
  });
};

const onAfterUpload = (file) => {
  try {
    const fileRef = file;
    const im = gm.subClass({ imageMagick: true });

    const dest = {
      meta: {},
      path: fileRef.path.replace(/(png|jpeg)$/, 'jpg'),
      extension: 'jpg',
      type: 'image/jpeg',
    };

    let imageComputing = im(fileRef.path).autoOrient().gravity('Center');
    let size = Meteor.wrapAsync(imageComputing.size, imageComputing)();

    if (size.height > 1000 || size.width > 1000) {
      imageComputing = imageComputing.resize(1000, 1000);
    }

    imageComputing = imageComputing
      .strip()
      .type('Optimize')
      .compress('JPEG')
      .quality('75')
      .interlace('plane');

    Meteor.wrapAsync(imageComputing.write, imageComputing)(dest.path);
    dest.size = fs.statSync(dest.path).size;

    if (fileRef.path !== dest.path) {
      fs.unlinkSync(fileRef.path);
    }

    size = Meteor.wrapAsync(imageComputing.size, imageComputing)();

    const originalDest = dest;
    dest.meta = {
      createdAt: new Date(),
      name: fileRef.name.replace(/\.[a-z]*$/i, ''),
      width: size.width,
      height: size.height,
    };

    const upd = {
      $set: {
        versions: {
          original: originalDest,
        },
        meta: dest.meta,
        path: dest.path,
        extension: dest.extension,
        type: dest.type,
      },
    };

    Images.update(fileRef._id, upd);

    fileRef.path = dest.path;
    fileRef.size = dest.size;
    fileRef.type = dest.type;
    fileRef.extension = dest.extension;
    fileRef.meta = dest.meta;
    fileRef.versions.original = dest;

    sendToStorage(fileRef);
  } catch (exception) {
    fs.unlink(file.path, (error) => { if (error) { console.log(error); } });
    Images.remove({ _id: file._id }, (error) => { if (error) { console.log(error); } });

    throw new Meteor.Error('500', `[onAfterUpload] ${exception}`);
  }
};

const onBeforeRemove = (cursor) => {
  // TODO: Implement onBeforeRemove
};

const interceptDownload = (http, fileRef, version) => {
  try {
    if (
      fileRef &&
      fileRef.versions &&
      fileRef.versions[version] &&
      fileRef.versions[version].meta &&
      fileRef.versions[version].meta.pipeFrom
    ) {
      Images.serve(http, fileRef, fileRef.versions[version], version, request({
        url: fileRef.versions[version].meta.pipeFrom,
        headers: _.pick(http.request.headers, 'range', 'cache-control', 'connection'),
      }));

      return true;
    }

    return false;
  } catch (exception) {
    throw new Meteor.Error('500', `[interceptDownload] ${exception}`);
  }
};

export { onAfterUpload, onBeforeRemove, interceptDownload };

```  
## Server Log
> I20170530-17:41:50.272(-3)? [FilesCollection.storagePath] Set to: /meteor-projects/files-upload/uploads
> I20170530-17:41:55.473(-3)? [FilesCollection] [download(/uploads/Images/MqmdCLhSpggYQRDNK/original/MqmdCLhSpggYQRDNK.jpg, original)]
> I20170530-17:41:55.579(-3)? [FilesCollection] [serve(/home/martin/Proyectos-Full-Stack/proyecto-dinamo/dinamo-server-meteor/uploads/MqmdCLhSpggYQRDNK.jpg, original)] [200]
> W20170530-17:41:55.589(-3)? (STDERR) [FilesCollection] [download(/uploads/Images/MqmdCLhSpggYQRDNK/original/MqmdCLhSpggYQRDNK.jpg)] [_404] File not found
> I20170530-17:41:55.891(-3)? Exception in callback of async function: Error: Can't set headers after they are sent.
> I20170530-17:41:55.891(-3)?     at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
> I20170530-17:41:55.891(-3)?     at ServerResponse.res.setHeader (/home/martin/.meteor/packages/webapp/.1.3.15.1sgofpa++os+web.browser+web.cordova/npm/node_modules/connect/lib/patch.js:134:22)
> I20170530-17:41:55.891(-3)?     at ServerResponse.setWriteHeadHeaders (/home/martin/.meteor/packages/webapp/.1.3.15.1sgofpa++os+web.browser+web.cordova/npm/node_modules/on-headers/index.js:82:19)
> I20170530-17:41:55.892(-3)?     at ServerResponse.writeHead (/home/martin/.meteor/packages/webapp/.1.3.15.1sgofpa++os+web.browser+web.cordova/npm/node_modules/on-headers/index.js:41:36)
> I20170530-17:41:55.892(-3)?     at FilesCollection.module.runModuleSetters.FilesCollection._404 (packages/ostrio_files/files.coffee:2263:19)
> I20170530-17:41:55.892(-3)?     at packages/ostrio_files/files.coffee:2306:23
> I20170530-17:41:55.892(-3)?     at packages/ostrio_files/files.coffee:18:55
> I20170530-17:41:55.892(-3)?     at runWithEnvironment (packages/meteor.js:1176:24)

**Comment by dr-dimitru** [comment]
Hello @mgscreativa ,

You forgot to return `true`, see my changes below:

```diff
import { Meteor } from 'meteor/meteor';
import { FilesCollection } from 'meteor/ostrio:files';

const Images = new FilesCollection({
  debug: true,
  throttle: false,
  storagePath: () => `${Meteor.absolutePath}/uploads`,
  downloadRoute: '/uploads',
  collectionName: 'Images',
  allowClientCode: false,
  onBeforeUpload: (file) => {
    if (file.size > 10485760) {
      return 'Please upload image, with size equal or less than 10MB.';
    }

    if (!/png|jpg|jpeg/i.test(file.extension)) {
      return `${file.extension}'s files are not allowed for upload.`;
    }

    return true;
  },
  onAfterUpload: (fileRef) => {
    import { onAfterUpload } from '../../modules/server/upload-files';

    onAfterUpload(fileRef);
  },
  onBeforeRemove: (cursor) => {
    if (Meteor.isServer) {
      console.log('Running onBeforeRemove on the server');
    } else {
      console.log('Running onBeforeRemove on the client');
    }

    import { onBeforeRemove } from '../../modules/server/upload-files';

    onBeforeRemove(cursor);
  },
  interceptDownload: (http, fileRef, version) => {
    import { interceptDownload } from '../../modules/server/upload-files';

+   return interceptDownload(http, fileRef, version);
  },
});

export default Images;
```

**Comment by mgscreativa** [comment]
Done! Thank you!
