### ISSUE TITLE
internel error when query in url

### ISSUE THREAD

**Issue by daorren** [VeliovGroup/Meteor-Files#482]
> meteor-files @1.8.0

Whenever there is query in file url, there will be a internel server error

Here I take the Demo url for example, https://files.veliov.com/cdn/storage/uploadedFiles/q8h8KfLqWnJMMBry6/original/q8h8KfLqWnJMMBry6.gif?imageView&utm_source=hackernews

This will cause this(in my development)

```
SyntaxError: Unexpected token ,
   at Object.parse (native)
   at Object.handle (packages/ostrio_files/files-server.coffee:828:60)
   at next (/Users/jojoma/.meteor/packages/webapp/.1.3.16.15ockc9++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:174:15)
   at Object.handle (packages/ostrio:cookies/cookies.js:430:17)
   at next (/Users/jojoma/.meteor/packages/webapp/.1.3.16.15ockc9++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:174:15)
   at Object.handle (packages/cfs_http-methods.js:444:12)
   at next (/Users/jojoma/.meteor/packages/webapp/.1.3.16.15ockc9++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:174:15)
   at Object.handle (packages/meteorhacks_inject-initial.js:242:3)
   at next (/Users/jojoma/.meteor/packages/webapp/.1.3.16.15ockc9++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:174:15)
   at Function.app.handle (/Users/jojoma/.meteor/packages/webapp/.1.3.16.15ockc9++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:182:3)
```

While 
https://files.veliov.com/cdn/storage/uploadedFiles/q8h8KfLqWnJMMBry6/original/q8h8KfLqWnJMMBry6.gif?imageView=1&utm_source=hackernews
with params and no query, all is fine.

However, see [meteor http call](http://docs.meteor.com/api/http.html#HTTP-call), both query and params should be valid

> The query option replaces the query string of url. Parameters specified in params that are put in the URL are appended to any query string. For example, with a url of '/path?query' and params of { foo: 'bar' }, the final URL will be '/path?query&foo=bar'.

And I found this in the package, which may caused the problem

```coffeescript
query: if request._parsedUrl.query then JSON.parse('{"' + decodeURI(request._parsedUrl.query).replace(/"/g, '\\"').replace(/&/g, '","').replace(/=/g,'":"') + '"}') else {}
```

**Comment by dr-dimitru** [comment]
Hello @daorren ,

This is definitely a bug. Interesting what it starts in [`webapp`](https://atmospherejs.com/meteor/webapp) package. Where `webapp` package has an outdated dependency on [`connect@2.30.2`](https://github.com/senchalabs/connect) package.

This is not actually that matter.
We just confirmed this is a bug on our end. Should be fixed soon.

Thank you for reporting this critical bug!

**Comment by daorren** [comment]
@dr-dimitru you're welcome! Hope it get fixed soon
