### ISSUE TITLE
Dropbox Integration - cant find dropbox module

### ISSUE THREAD

**Issue by fillipefeitosa** [VeliovGroup/Meteor-Files#679]
### I'm having an issue:
  - Meteor cant find Dropbox modules
  - Current Version of "ostrio:files and ostrio:autoform-files"
  - Meteor 1.8.2
  - Error appears on Server Console Log and the Client Browser
  - Is it *Client* or *Server* issue?

# Installed Using the Following Command:
meteor@f274fb7659e5:~/app$ meteor npm install --save dropbox@=0.10.3
+ dropbox@0.10.3
added 3 packages from 5 contributors and audited 781 packages in 4.505s
found 1 critical severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

---
  
I am using the same code provided in the Dropbox integration. Any help?

Thanks for your time.

/home/meteor/.meteor/packages/meteor-tool/.1.8.0_2.1om3lwx.sy8++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
						throw(ex);
						^

Error: Cannot find module "dropbox"
    at Object.require (/home/meteor/app/.meteor/local/build/programs/server/boot.js:295:24)
    at images.js (imports/api/images/images.js:32:19)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/home/meteor/.meteor/packages/modules/.0.13.0.176lf51.fi71++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
    at team.js (imports/api/team/team.js:1:265)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/home/meteor/.meteor/packages/modules/.0.13.0.176lf51.fi71++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
    at register-api.js (imports/startup/server/register-api.js:1:198)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
    at Module.moduleLink [as link] (/home/meteor/.meteor/packages/modules/.0.13.0.176lf51.fi71++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/reify/lib/runtime/index.js:38:38)
    at index.js (imports/startup/server/index.js:1:37)
    at fileEvaluate (packages/modules-runtime.js:336:7)
    at Module.require (packages/modules-runtime.js:238:14)
Exited with code: 1
Your application is crashing. Waiting for file change.

**Comment by fillipefeitosa** [comment]
Friend,

I tried using your lib many ways. I even promote it on Meteor Foruns a couple of times.

I think integrations are using versions not supported anymore. This is Dropbox integrations, same goes for the Google Cloud...

=> Meteor server restarted                    
W20190326-17:30:35.105(0)? (STDERR) Dropbox API error 400 from POST https://api-content.dropbox.com/1/files_put/auto/RCNxAhyAr5Fpv5rwP-original.xlsx :: {"error": "v1_retired"} { triesSend: 10 }

**Comment by jankapunkt** [comment]
Hi @fillipefeitosa 

yes the V1 is deprecated and v2 is encouraged: https://github.com/dropbox/dropbox-sdk-js

The guide needs to be updated. Did you manage to integrate v2 on your own?

**Comment by jankapunkt** [comment]
Related: https://github.com/VeliovGroup/Meteor-Files/issues/112

**Comment by fillipefeitosa** [comment]
No I did not. 

Right now I am self hosting. But I really wanted to use some integration.

Checking your references.

**Comment by dr-dimitru** [comment]
Closed in favor of #112
