### ISSUE TITLE
Issue while uploading image

### ISSUE THREAD

**Issue by kaushalbrahmbhatt38** [VeliovGroup/Meteor-Files#724]
```
I20200123-18:57:34.751(5.5)? Exception while invoking method 'collections.images.insert' TypeError: Cannot read property 'insert' of undefined
I20200123-18:57:34.753(5.5)?     at MethodInvocation.collections.images.insert (imports/api/collections/methods.js:20:31)
I20200123-18:57:34.753(5.5)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
I20200123-18:57:34.753(5.5)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
I20200123-18:57:34.754(5.5)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
I20200123-18:57:34.754(5.5)?     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
I20200123-18:57:34.754(5.5)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
I20200123-18:57:34.754(5.5)?     at Promise (packages/ddp-server/livedata_server.js:715:46)
I20200123-18:57:34.755(5.5)?     at new Promise (<anonymous>)
I20200123-18:57:34.755(5.5)?     at Session.method (packages/ddp-server/livedata_server.js:689:23)
I20200123-18:57:34.755(5.5)?     at packages/ddp-server/livedata_server.js:559:43
```
### Collection constructor server Code :
```
import { FilesCollection } from 'meteor/ostrio:files';

const Collections_Images = new FilesCollection({
	collectionName: 'collections_images',
	storagePath: 'uploads/Collections-Images',
	allowClientCode: false,
	onBeforeUpload(file) {
		// Allow upload files under 10MB, and only in png/jpg/jpeg formats
		if (file.size <= 10485760 && /png|jpg|jpeg/i.test(file.extension)) {
			return true;
		}
		return 'Please upload image, with size equal or less than 10MB';
	}
});

export default Collections_Images;
```
### Created method Code :
```
import { Meteor } from 'meteor/meteor';
import { Collections_Images } from './collections_img.js';

Meteor.methods({
  'collections.images.insert'(images) {
    return Collections_Images.insert({
          file : images,
          streams: 'dynamic',
          chunkSize: 'dynamic',
        })
  },
});

```
### Client side js code:
```
"change #myFileInput" : function(event){
        const images = event.currentTarget.files[0];
        Meteor.call('collections.images.insert',images, (error) => {
            if(error){
                alert("collection image insert : "+error.message);
            }
            else{
                images=null;
            }
        });
    }
```

**Comment by jankapunkt** [comment]
You need to change your export from 

`export default Collections_Images`

to 

```
export const Collections_Images = new FilesCollection({
	collectionName: 'collections_images',
	storagePath: 'uploads/Collections-Images',
	allowClientCode: false,
	onBeforeUpload(file) {
		// Allow upload files under 10MB, and only in png/jpg/jpeg formats
		if (file.size <= 10485760 && /png|jpg|jpeg/i.test(file.extension)) {
			return true;
		}
		return 'Please upload image, with size equal or less than 10MB';
	}
});
```

or your import from 

`import { Collections_Images } from './collections_img.js';`

to

`import Collections_Images from './collections_img.js';`

**Comment by kaushalbrahmbhatt38** [comment]
Thanks @jankapunkt but
It will give error like :
```
I20200123-21:19:28.611(5.5)? Exception while invoking method 'collections.images.insert' TypeError: Collections_Images.insert is not a function
I20200123-21:19:28.613(5.5)?     at MethodInvocation.collections.images.insert (imports/api/collections/methods.js:20:31)
I20200123-21:19:28.613(5.5)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
I20200123-21:19:28.613(5.5)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
I20200123-21:19:28.614(5.5)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
I20200123-21:19:28.614(5.5)?     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
I20200123-21:19:28.614(5.5)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
I20200123-21:19:28.615(5.5)?     at Promise (packages/ddp-server/livedata_server.js:715:46)
I20200123-21:19:28.615(5.5)?     at new Promise (<anonymous>)
I20200123-21:19:28.615(5.5)?     at Session.method (packages/ddp-server/livedata_server.js:689:23)
I20200123-21:19:28.615(5.5)?     at packages/ddp-server/livedata_server.js:559:43
```

**Comment by dr-dimitru** [comment]
Hello @kaushalbrahmbhatt38 ,

`.insert()` method is *Client* only. No need to send file over the method. Update client-side code to:

```js
{
  "change #myFileInput" : function(event){
        const images = event.currentTarget.files[0];
        Collections_Images.insert({
          file : images,
          streams: 'dynamic',
          chunkSize: 'dynamic',
        });
    }
}
```

RTFM

Feel free to close it in case if the issue is solved on your end.

**Comment by kaushalbrahmbhatt38** [comment]
Thanks @dr-dimitru,

Firstly i already tried what you said but it gives me the same error on browser console thats why i'm go for method just only for trying purpose.

**Comment by kaushalbrahmbhatt38** [comment]
But now my problem is solved. As `.insert(update)` method is on client side. 
And Correct importing of Collection_img.js is : 
`import Collections_Images from './collections_img.js';`
because i'm exporting default from './collections_img.js'

Again Thanks @jankapunkt and @dr-dimitru for your help.

**Comment by dr-dimitru** [comment]
@kaushalbrahmbhatt38 I'm glad it's solved. 
Feel free to reopen it in case if the issue is still persists on your end.

Please support this project with:
 - Star this package on GitHub;
 - Like [at Facebook](https://www.facebook.com/veliovgroup);
 - Follow [on Twitter](https://twitter.com/veliovgroup);
 - Support [via patreon](https://patreon.com/dr_dimitru);
 - Support [via PayPal](https://paypal.me/veliovgroup);
 - Check and star our [other open source projects on GitHub](https://github.com/VeliovGroup).
